### ISSUE TITLE
Mouse passthrough rather slow

### ISSUE THREAD

**Issue by Empoga** [StrateimTech/hid-api-rs#1]
Hey mate! Appriciate your work. It implemented your project on a respaberry pi 4b, generallay it seems to work (except for the side buttons  mouse 4 and 5, but that's not what the issue is about).

When moving the mouse it feels like it lags behind, you dont really notice it at first but when moving windows around you can see that it is not as responsive as without the pi. 
I understand that we have an additonal hardware device handling all the reports but i was wondering if you noticed this yourself.
Best to describe is it feels like you are moving your mouse on a 60hz screen but you have a 144hz screen. The movememnt should be more fluent.

**Comment by EthoIRL** [comment]
Cheers, I'm glad you like my work. Regarding the slow/laggy I've known about it for a quite a while now just haven't gotten around to fixing it sorry about that. The rpi 4b's hardware should be able to handle +1000hz mouse's without a hitch. 

This #2 pull request should add both side buttons and fix the slow issue to some degree (at least on my end). **Please note you'll have to update your report descriptor (the example script, you can just replace it) as it adds functionality for the side buttons and will not work without the updated version.**
